### ISSUE TITLE
How to properly use this package? Setup errors

### ISSUE THREAD

**Issue by mungai-njoroge** [mfuu/vue3-virtual-drag-list#1]
This package looks promising. Thanks for the good work. However, I'm trying to use implement the example on the readme before I implement (on this project: [swing-client](https://github.com/geoffrey45/swing-client)) and I'm running into errors. Here's my template code:

```vue
<virtual-list
  :data-key="'id'"
  :data-source="items"
  :draggable="'#drag'"
  style="height: 500px"
  @ondragstart="logDragStart"
>
  <template #item="{ record, index, dataKey }">
    <i id="drag" class="drag">drag me</i>
    <span>{{ (record.text, dataKey, index) }}</span>
  </template>
</virtual-list>

<script setup lang="ts">
import VirtualList from "vue-virtual-draglist";

const items = ref([
  { id: "1", text: "abc" },
  { id: "2", text: "def" },
]);

function logDragStart() {
  console.log("dragging ...");
}
<script>
```
This is how the list looks on inspecting.
![image](https://user-images.githubusercontent.com/48554537/221177317-1b2aeab4-ec0a-4f35-b1b1-1b2ebd02095d.png)

ON the UI, the list is draggable, but there are a lot of errors on the console. 
![image](https://user-images.githubusercontent.com/48554537/221175381-79bfa1ec-2dd7-420c-af18-287b139b63a0.png)
There's errors like the above for each rendered list item.
On drag start, the `logDragStart` function is called, followed by the following errors on the console.
![image](https://user-images.githubusercontent.com/48554537/221175923-26b3c62f-4ee6-4765-bb78-99fe4d0a2058.png)

Is there something wrong with my code? How do I get it to work? Would you mind updating this package. I'll help with the testing.

**Comment by geoffrey45** [comment]
I can't find the demo code anywhere. Can you share the repo, I want to see the implementation. Thank you.

**Comment by mfuu** [comment]
I will update as soon as possible due to errors caused by unfixed dependency package version

**Comment by geoffrey45** [comment]
Thank you.

**Comment by mfuu** [comment]
@geoffrey45 Try to use the latest version to solve the problem

**Comment by geoffrey45** [comment]
@mfuu Let me give it a try ASAP

**Comment by geoffrey45** [comment]
@mfuu I'm having the same issues with the latest package `^3.0.3`

**Comment by mfuu** [comment]
@geoffrey45 I fixed it in the latest version, please try it again, thanks for your issue

**Comment by geoffrey45** [comment]
The errors and `[object object]` in the dom are now gone, but this warning is still there. Is there any way to fix it?

![image](https://user-images.githubusercontent.com/48554537/221411397-8f5a2820-e14b-463c-b6a4-8c6790fe1396.png)

**Comment by mfuu** [comment]
This is the recommended functional writing method in the vue3 version. I will rewrite and update the code later

**Comment by Coderhyp** [comment]
hello 想问下现在vue3版本的是可用的吗 为什么我监听不到bottom事件
