### ISSUE TITLE
Dynamic line height bug

### ISSUE THREAD

**Issue by jimmyrogue** [mfuu/vue3-virtual-drag-list#18]
Hi

my component is a dynamic image list

so the height isn't const

when I scroll down everything is ok but when I scroll up

the scroll position will jump back to where load start

pls help me 

thanks

![20240329_182232](https://github.com/mfuu/vue3-virtual-drag-list/assets/6006189/18706f0e-f642-432a-927a-98c0a6fa21ed)

**Comment by mfuu** [comment]
@jimmyrogue 
Could you provide test case code, similar to [codesandbox](https://codesandbox.io/s/vue3-virtual-draglist-6l3pw0?file=/src/components/Virtual.vue)?

**Comment by jimmyrogue** [comment]
@mfuu  here: [https://codesandbox.io/p/sandbox/vue3-virtual-draglist-forked-vqskys?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clugpbgbk00063b6ipczf90lp%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clugpbgbk00023b6i2n2scl0i%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clugpbgbk00033b6iabkcn98f%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clugpbgbk00053b6ir77qtnsw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B43.99988095592393%252C56.00011904407607%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clugpbgbk00023b6i2n2scl0i%2522%253A%257B%2522id%2522%253A%2522clugpbgbk00023b6i2n2scl0i%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clugpbgbk00053b6ir77qtnsw%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clugpbgbk00043b6iuodfkp7f%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clugpbgbk00053b6ir77qtnsw%2522%252C%2522activeTabId%2522%253A%2522clugpbgbk00043b6iuodfkp7f%2522%257D%252C%2522clugpbgbk00033b6iabkcn98f%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clugpbgbk00033b6iabkcn98f%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D](url)

**Comment by mfuu** [comment]
@jimmyrogue It's caused by the size change of the image before and after loading.

**Comment by jimmyrogue** [comment]
@mfuu thanks but  if I still need to calc the height of image by a function or dynamic, how to do it correctly ?

**Comment by mfuu** [comment]
@jimmyrogue I am trying to solve it, you can re-open the issue if you want

**Comment by mfuu** [comment]
@jimmyrogue Try to pass an estimated size with `size` prop, like:
```vue
<virtual-list :size="50"></virtual-list>
```

**Comment by jimmyrogue** [comment]
@mfuu  thanks and I find if I calc the height earlier the problem will solve
