### ISSUE TITLE
@click not work on mobile (Pad)

### ISSUE THREAD

**Issue by jimmyrogue** [mfuu/vue3-virtual-drag-list#20]
Click event not trigger on Pad or Mobile mode.

here is test link,  click "click test"

<img width="547" alt="image" src="https://github.com/mfuu/vue3-virtual-drag-list/assets/6006189/52bc30a2-1cdf-4ae2-bb41-835e950ca97c">

[TEST](https://codesandbox.io/p/sandbox/vue3-virtual-draglist-forked-nv6ntk?file=%2Fsrc%2Fcomponents%2FVirtual.vue%3A25%2C44-26%2C42)

**Comment by mfuu** [comment]
@jimmyrogue Please update to the lasted version(3.2.4) to check if works correct.

**Comment by jimmyrogue** [comment]
@mfuu  thanks  it works
