### ISSUE TITLE
When switching list data sources, there is a display problem

### ISSUE THREAD

**Issue by vaseala** [mfuu/vue3-virtual-drag-list#22]
I created a git repository to reproduce this issue
https://github.com/issuebox/vue-virtual-drag-list-issue

* The default status display is normal
* Then click `button1`,  display normal, it show 2 items;
* Then click `button2`,  I want to show 5 items, but it show 4items, ant the first item's place is blank.
* Then click `button3`, same problem
* Then click `button1`,  Then click `button2` ...., Totally messed up

Apart from this problem, I think the `vue3-virtual-drag-list`  is great and I like it very much and thank you for providing such a great vue plugin.

**Comment by mfuu** [comment]
@vaseala Thank you for your approval and use, I will review and fix this problem as soon as possible.

**Comment by mfuu** [comment]
@vaseala Sorry for the late reply. Please update to the lasted version to solve the problem.

**Comment by vaseala** [comment]
> @vaseala Sorry for the late reply. Please update to the lasted version to solve the problem.

Just tested it with version 3.3.8, it works! Thanks very much!
