### ISSUE TITLE
Code examples

### ISSUE THREAD

**Issue by theSilverFisch** [mfuu/vue3-virtual-drag-list#3]
Could you provide code examples for your demo components? The List somewhat works but I can't seem to manipulate the output in the slot template no matter what I add there. I also seem to be unable to deactivate the drag feature.

Is there an API documentation anywhere? 

Regards

**Comment by theSilverFisch** [comment]
But how do you make the items into "infinity-items" as in your demo? For me it currently just renders the amount of items I defined in keeps

**Comment by theSilverFisch** [comment]
@mfuu Any chance to get an updated documentation for the examples soonish? So far I seem not to be able to let it render more dataItems than I have defined in the "keeps"

**Comment by mfuu** [comment]
@theSilverFisch Sorry to reply so late, I will update the version in the near future to fix some known issues and update the documentation. Thank you for your patience.

**Comment by theSilverFisch** [comment]
> @theSilverFisch Sorry to reply so late, I will update the version in the near future to fix some known issues and update the documentation. Thank you for your patience.

Awesome! Thanks a lot my friend!
